carbon-design-system/ibm-security

src/components/Tearsheet/TearsheetSmall/_index.scss
- Resolves #10 
- import `ScrollGradient` scss into `TearsheetSmall` (which then gets imported into `Tearsheet`)
- Storybook - https://deploy-preview-tearsheet-scss-imports--ibm-security.netlify.com
=> fix(tearsheet-small): import scrollgradient scss

.github/PULL_REQUEST_TEMPLATE.md
- Remove the example deploy link from the PR template because Netlify will post the links in the comments + the deploy link will update if new commits are pushed. So the PR creator's posted link would likely become stale quickly. We can just rely on the Netlify bot 👍
=> docs: remove deploy link example from pr template

src/components/CodeSnippet/CodeSnippet.stories.js, src/components/CodeSnippet/_index.scss, src/components/CopyButton/CopyButton.stories.js, src/components/CopyButton/_index.scss, src/components/CopyButton/index.js
- Resolves #37 
- proxy `CopyButton` component and create story
- import `CopyButton` styles into `CodeSnippet`
- centered `CodeSnippet` stories
=> feat(copy-button): proxy copy button and import styles in code snippet

src/components/CopyButton/CopyButton.stories.js, src/components/_index.scss, src/index.js
NOTE: this should have been done in #38 😅 
- export `CopyButton`
- add component category to story
- add wrapper with `position: relative` to story (required if you want the button to be centered)
=> fix(copy-button): export component, add category and wrapper to story

src/components/DatePicker/DatePicker.stories.js
- Resolves #50 
- remove unnecessary story that had a repeated name & was generating a console warning (Carbon doesn't have that story in their environment: http://react.carbondesignsystem.com/?path=/story/datepicker--simple)
=> docs(date-picker): remove superfluous story causing name collision

src/components/Header/__tests__/__snapshots__/Header.spec.js.snap, src/components/Header/_mocks_/index.js
- Resolves #57 
- converts `id` value in mocks to a string
**NOTE:** alternatively we could change the proptype for for `accounts.id` to a `number`... but while personally I would prefer that, that change seems like a bigger deal given that this component is currently in use as-is. So with this change, we'd only be affecting our own mocks (and resulting tests)
=> chore(header): convert account id in mocks to string

src/components/SearchBar/__tests__/SearchBar.spec.js, src/components/SearchBar/__tests__/__snapshots__/SearchBar.spec.js.snap
- Resolves #58 
- `scopesTypeLabel` is required with `scopes` prop is used, so I added it where necessary to the tests to remove the prop types error identified in #58
=> chore(search-bar): update tests with required prop

src/components/SearchBar/SearchBar.js, src/components/SearchBar/SearchBar.stories.js
- Resolves #72 
- add `translateWithId` prop to `SearchBar`, then pass through to child `MultiSelect`
- show `translateWithId` prop in use in the scopes stories
=> fix(search-bar): pass through translatewithid prop to multiselect child

.storybook/index.scss, src/components/ICA/ICA.stories.js
- Resolves #23 
- add "with ICA wall" example that shows how to use grid classes to display multiple ICA components
- reformat a couple of the storybook names to match convention used for other stories ("with" etc)
- add `box-sizing: border-box` reset to Storybook (⚠️ NOTE: this is necessary to use the grid, as we don't apply a reset globally)
=> docs(ica): add grid example and add box-sizing reset to storybook styles

src/components/Tooltip/Tooltip.stories.js
- center the `Tooltip` stories so that the tooltip isn't cut off at the ends of the storybook preview frame
=> docs(tooltip): center tooltip stories

src/components/DataDecorator/DataDecorator.js, src/components/DataDecorator/__tests__/__snapshots__/DataDecorator.spec.js.snap
- Resolves #88
- add `noIcon` prop to `DataDecorator` and pass to `Decorator`
=> fix(data-decorator): add noIcon prop that gets passed to inner decorator

src/components/Checkbox/Checkbox.stories.js
- Resolves #78 
- adds a display name for the checkbox
Compare the proptable in the Netifly deploy (when it finishes) to this prop table: https://ibm-security.carbondesignsystem.com/?path=/story/components-checkbox--checked
=> docs(checkbox): add display name so prop table is correct in stories

src/components/StackedNotification/StackedNotification.js, src/components/StackedNotification/StackedNotification.stories.js, src/components/StackedNotification/_mocks_/index.js
- Resolves #115
- Modified props to be in Storybook fashion with knobs available.
- Added `centered` decorator
- visit storybook
=> docs(stacked-notification): add knobs to storybook

src/components/Tearsheet/__tests__/__snapshots__/Tearsheet.spec.js.snap
- regenerate snapshots for `Tearsheet`, since the button has changed
=> chore(tearsheet): update tearsheet snapshots to fix tests

src/components/InlineLoading/InlineLoading.stories.js, src/components/StatusIndicator/StatusStep/StatusStep.js
- Resolves partially #104
- Update deprecated `success` `InlineLoading` prop in `StatusIndicator` to `status`
=> fix(status-indicator): update deprecated `InlineLoading` prop

src/components/TagWallFilter/__tests__/__snapshots__/TagWallFilter.spec.js.snap, src/components/Tearsheet/Tearsheet.js, src/components/Tearsheet/TearsheetSmall/TearsheetSmall.js
20x20 Close20 icon is used in PanelV2 and Modal and it should also be used in Tearsheet components
- Resolves #126 
- replace `Close16` 16x16 icon with `Close20` 20x20.
- check if the close icon size is the same as in `PanelV2` or `Modal`
=> fix(tearsheet, tearsheet-small): replace Close16 icons with Close20

src/components/MultiSelect/MultiSelect.stories.js
Apparently the knobs were sometimes crashing when doing some changes on them, moving filterable from the first key of props seems to fix this issue (not sure why though).
- Resolves #121 
- add and reorder props to match these from carbon-components
- add `centered` decorator
As reported in the issue, **not only** changing the values in `listBoxMenuIconTranslationIds` were crashing knobs, but _any_ other change was also crashing the knobs (you can verify that by changing some knobs in the [MultiSelect](https://ibm-security.carbondesignsystem.com/?path=/story/components-multiselect--default)
- check if changing knobs will crash the knobs sidebar (crash == options to change will disappear,  and refresh is needed)
=> docs(multi-select): add and reorder props to match these from carbon-components

src/components/TagWallFilter/Filter/_mixins.scss
- Resolves #139 
- Remove redundant overrides to align search with `Search` and allow Carbon list item styles to display
=> fix(filter): refactor styles and remove overrides

src/components/StatusIndicator/_mixins.scss
- Resolves #148 
- removed `padding-top` and `padding-bottom` from `incomplete` icon as it was interfering with the icon size. 
- check if the `incomplete` icon on `StatusIndicator` component is now properly sized.
If someone has an idea why these paddings were decreasing the icon size, I'd greatly appreciate any input as I'm pretty clueless about this specific thing 😄 .
Also, I've noticed that the `complete` icon is 16x16 px size and it doesn't look the best IMO for example in `StatusIndicator` - `Dynamic` story, when the icon sizes change from 20x20 to 16x16. (not sure if it's supposed to be like this, or it is a bug)
=> fix(status-indicator): remove additional paddings for incomplete icon

src/components/Select/_index.scss
- Resolves #149 
- resets the `text-rendering` style rule because `text-render: optimizeLegibility` appears to cause `select` elements in Safari to crash. See my comment here for webkit bug info & breakdown: https://github.com/carbon-design-system/ibm-security/issues/149#issuecomment-542298389
To see Safari breaking:
- Go to https://ibm-security.carbondesignsystem.com/?path=/story/components-select--default (or `Pagination`, which also uses a `Select` component that has an underlying `select` element) 
- Try interacting with the `Select` -- Safari will quickly "beach ball" and require a force quit.
- Force quit Safari
To see it fixed:
- Open the Netlify deployment for this PR (https://deploy-preview-157--ibm-security.netlify.com/) and view the `Select` component
- Try interacting with the …
=> fix(select): apply text-rendering style to stop safari from crashing

README.md
- Resolves #160 
- replace dead link to working one for babel imports plugin
- click the link -- should properly redirect
=> docs(readme): fix dead babel imports plugin link

src/components/Nav/Nav.stories.js, src/components/Nav/NavItem/NavItem.js, src/components/Nav/NavItem/__tests__/__snapshots__/NavItem.spec.js.snap, src/components/Nav/NavItemLink/NavItemLink.js, src/components/Nav/NavItemLink/index.js, src/components/Nav/NavList/__tests__/__snapshots__/NavList.spec.js.snap, src/components/Nav/__tests__/__snapshots__/Nav.spec.js.snap
- Partially addresses #31 for the `Nav` only (followup to feedback from https://github.com/carbon-design-system/ibm-security/pull/33) 
- create `NavItemLink` that accepts custom tag
- pass through extra props in `NavItem` to `NavItemLink` (so that a custom routing element with its given props can be used)
- update story and snapshots
=> feat(nav-item-link): add component that accepts custom tag, include in nav

src/components/DataTable/TableToolbarDownload.js
- Populating row property with empty string if not defined
- Only allowing exporting when rows and headers exist
- Refer to [original PR](https://github.com/carbon-design-system/ibm-security/pull/130)
=> fix(table-toolbar-download): require rows and headers for export, set row property to empty string if not defined

src/components/Select/_index.scss
- Resolves #168 
- change focus text color to `$text-01` to resolve issue in Firefox
- view the netlify deployment in Firefox & interact with the `Select` component
=> fix(select): add focus text color override

src/components/SearchBar/_mixins.scss
- remove `border: 0` on the search button that was overriding the `Button` component focus border (without this change, if you focus on this button, it doesn't have a visible focus border)
- remove unnecessary background color rules for the submit button
=> fix(search-bar): remove styles overriding focus state

src/components/Tearsheet/TearsheetSmall/_mixins.scss
- Allow the content to horizontally scroll within the tearsheet if it's not styled to break
=> fix(tearsheet-small): add content overflow to prevent scrolling

src/components/Accordion/_index.scss
- vertically center items in the `Accordion` heading
=> fix(accordion): vertically center items in heading

src/components/DataDecorator/Decorator/Decorator.js, src/components/DataDecorator/_mixins.scss
- Resolves #198 
- Revert `viewBox`
- Align inline styles with default styles, add only height and padding variations
=> fix(decorator): provide only necessary variations for inline, vertically align, revert viewbox

src/components/DataTable/_index.scss, src/components/Tearsheet/_mixins.scss
- Resolves #206
- Adjust `DataTable` overflow `z-index` to work with `Tearsheet`
- Add Carbon imports for modularity
=> fix(data-table): adjust overflow `z-index` to work with `Tearsheet`

README.md, docs/themes/README.md
- Remove references to Carbon's themes to avoid confusion by consuming developers
- Provide more emphasis to theme documentation in `README.md`
=> docs(themes): update theme documentation, remove Carbon references

src/components/ComboButton/ComboButton.js, src/components/ComboButton/ComboButton.stories.js, src/components/ComboButton/__tests__/__snapshots__/ComboButton.spec.js.snap, src/components/ComboButton/_mixins.scss
- Resolves partially https://github.com/carbon-design-system/ibm-security/issues/178
- Tweaks placement, creating a nested group to create the layout that the menu item's width is derived from
- Add a `ComboButton` inside a div without a fixed width
- Menu should no longer occupy 100% of wrapper div.
=> fix(combo-button): placement in scrollable parent

src/components/FilterPanel/FilterSubcategory/FilterSubcategory.js, src/components/FilterPanel/FilterSubcategory/__tests__/FilterSubcategory.spec.js
- Resolves #235 
- Refactor the `FilterSubcategory` component to use hooks
- Fix expand and collapse issues on the `FilterSubcategory` when selecting filters
- Go to the FilterPanel story in Storybook
- Check one of the visible filters
- Expand any of the collapsed subcategory accordions
=> fix(filter-subcategory): expand and collapse

src/components/Header/_mixins.scss
- Resolves #247 
- Add hyphenated word break for header popover title
1. Navigate to https://deploy-preview-250--ibm-security.netlify.com/?path=/story/patterns-header--with-active-user
2. In the `profile` knob, update `first_name` value to 'ReallyLongSampleFirstName'
=> fix(header): add hyphenated word break for popover title

src/components/StringFormatter/StringFormatter.js
* Updated`tooltipDirection` prop to match Carbon's propType & info for the `TooltipDefintion`: https://github.com/carbon-design-system/carbon/blob/dce56816e35055fe861b15d29d2f2d1eddbfeb53/packages/react/src/components/TooltipDefinition/TooltipDefinition.js#L69
```js
/**
* Specify the direction of the tooltip. Can be either top or bottom.
*/
direction: PropTypes.oneOf(['top', 'bottom']),
```
* change default of `className` to `null`
* rename the constant `children` to `content` so it is not confusion (`children` being the name of an important prop that is not used in this component)
=> fix(string-formatter): update prop tooltipDirection proptype, formatting

src/components/StringFormatter/_index.scss, src/components/SummaryCard/SummaryCard.js, src/components/SummaryCard/SummaryCard.stories.js, src/components/SummaryCard/SummaryCardAction/SummaryCardAction.js, src/components/SummaryCard/SummaryCardBatchActions/SummaryCardBatchActions.js, src/components/SummaryCard/SummaryCardBody/SummaryCardBody.js, src/components/SummaryCard/SummaryCardContainer/SummaryCardContainer.js, src/components/SummaryCard/SummaryCardFooter/SummaryCardFooter.js, src/components/SummaryCard/SummaryCardHeader/SummaryCardHeader.js, src/components/SummaryCard/SummaryCardSelect/SummaryCardSelect.js, src/components/SummaryCard/_mixins.scss
- Resolves #261
- add `StringFormatter` to `SummaryCardHeader` so that the title can be truncated with a proper, accessible Carbon tooltip
- add `...other` to each `SummaryCard` subcomponent to allow additional props passed through if necessary
- use `currentColor` for `Tooltip` trigger styles inside `StringFormatter` so as not to override `SummaryCardHeader` text color
- in components modified, change default value of `className` to `null`
- update `SummaryCard` story to include example of a truncated title
=> feat(summary-card): allow truncated title with tooltip, allow pass through props

src/components/PanelV2/PanelV2.js, src/components/PanelV2/__tests__/__snapshots__/PanelV2.spec.js.snap, src/components/PanelV2/_mixins.scss
- Resolves #276 
- reorder header so that close button comes first in DOM
- add `flex-direction: row-reverse` to header so that title/subtitle *appear* first
=> fix(panel-v2): reorder header to ensure that close button has initial focus

src/components/Nav/NavItemLink/NavItemLink.js
Warning in test output:
```
Warning: Component NavItemLink declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?
```
- change `NavItemLink.PropTypes` to `NavItemLink.propTypes`
=> chore(nav-item-link): update propTypes declaration

docs/migration/2.x-color.md, docs/migration/2.x-themes.md, docs/migration/migrate-to-2.x.md, src/globals/color/_index.scss, src/globals/layout/_index.scss, src/globals/theme/_functions.scss, src/globals/theme/_index.scss, src/globals/type/_index.scss
BREAKING CHANGE: The following SCSS has been removed:
- Color - `$security-color__gray-90--hover`
- Layout - `get-fixed-size`
- Themes - `theme` function and `$theme` variable
- Resolves #257 
- Remove deprecated color, layout, and themes methods
=> refactor: remove deprecated SCSS

CODE_OF_CONDUCT.md
Requirement for Netlify's Open Source plan - https://www.netlify.com/legal/open-source-policy
- Add 'Code of Conduct'
=> docs(code-of-conduct): add 'Code of Conduct'

src/globals/type/_index.scss
- Resolves #299
Expressive headings overrides are required for now because Carbon's vendor files for `10.9.0` of `carbon-components` has broken scss (i.e., unitless values are passed into a function & the result is an invalid string not a valid rem value).
So we need to include the css-reset after the expressive heading overrides so that our overrides get applied.
- move css-reset to after expressive headings overrides
=> build: move reset after expressive heading overrides to fix build

src/components/TrendingCard/__tests__/TrendingCard.spec.js, src/components/TrendingCard/__tests__/__snapshots__/TrendingCard.spec.js.snap
Tests generated the following error for `TrendingCard` --
```
console.error node_modules/react-dom/cjs/react-dom.development.js:530
Warning: <Link /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
in Link (created by TrendingCard)
in TrendingCard (created by Default)
in Default
```
- ~use HTML element `a` instead of `Link` for snapshot test~ make sure to import the `Link` component to use as a custom component in test
=> fix(trending-card): use Link component in test

package.json
- Resolves #335
- change `yarn docs` to only `git add` the `docs` directory only
=> chore: update docs command to git add docs dir only

src/components/PanelV2/PanelV2.stories.js
- per https://github.com/carbon-design-system/ibm-security/pull/308#discussion_r371760928, add knobs so that `title`, `subtitle`, and `aria-label` can be customized in storybook
=> docs(panelv2): add knobs for title, subtitle, and aria-label

src/components/Panel/PanelContainer.js, src/components/PanelV2/PanelV2.js
- Resolves #332 
- remove duplicate `aria-labelledby` in `hasScrollingContentProps`
- add logic to only apply `aria-labelledby` if there is a valid `title` or `subtitle`
Pull down the branch and experiment with the storybook by commenting out `title` and `subtitle` & checking rendered story to see there is no `aria-labelledby` attribute.
👉 Note that because we do not enforce/require many of this props, you can still generate a DAP error *if* you set `hasScrollingContent={true}` and remove `title`, `subtitle`, and `aria-label`. This error happens because `hasScrollingContent` adds `role="region"` to the panel content wrapper, which then *requires* some kind of label (but since there is no `aria-label`, or not `title` / `subtitle` to apply an `aria-labelledby`, the region is unlabeled and …
=> fix(panel): only apply aria-labelledby if title or subtitle provided

src/components/DataDecorator/_mixins.scss
Resolves #363
Add `vertical-align` property to ensure `Decorator` aligns itself correctly for each variation
=> fix(decorator): add `vertical-align` property

src/components/Accordion/Accordion.js, src/components/Accordion/__tests__/Accordion.spec.js
- add test to check for "start" alignment by default (opposite of Carbn's default)
- add test to check for custom class name passed through spread attribute
Also:
- fix custom class addition in `Accordion` 😳
=> fix(accordion): add alignment test, fix custom class addition

src/components/FilterPanel/FilterPanelGroup/FilterPanelGroup.js, src/components/FilterPanel/FilterPanelGroup/__tests__/FilterPanelGroup.spec.js
- Makes titles optional for filter panel groups
- Render a `FilterPanelGroup` without a title
=> fix(filter-panel-group): remove header if no title is provided

src/components/FilterPanel/FilterPanelAccordionItem/FilterPanelAccordiontItem.js
- Resolves #376 
- reorder elements so that `ul`s are only direct parents of `li` elements (nothing else was reordered)
=> fix(filter-panel-accordion-item): reorder elems so li are children of ul elems

src/components/FilterPanel/FilterPanelAccordionItem/FilterPanelAccordiontItem.js
- Resolves #393 
- Use the same theme color mechanism as the scroll gradient for the filter panel accordion item
- Go to the filter panel story
- Change the theme to g10
- Expand a scrollable filter panel accordion item
- Notice the gradient color
=> fix(filter-panel): accordion item themed gradient color

src/components/SummaryCard/_mixins.scss
- Resolves #419 
- remove `overflow: hidden` from `SummaryCard`
- Please verify that the component still looks correct. I'm not 100% sure why this overflow rule was necessary to begin with, but it doesn't seem so now. 🤔 And even if something is off, style-wise, we need to ensure these tooltips stay visible as they are higher priority.
=> fix(summary-card-action): remove overflow hidden so tooltip can be shown

src/components/Tile/Tile.stories.js, src/components/Tile/_index.scss
Resolves https://github.com/carbon-design-system/ibm-security/pull/241#pullrequestreview-367401980
- Update 'Selectable' story to 'Radio' as per Carbon's updates
- Refactor fixed style overrides and apply CSS reset to `TileGroup` - Carbon applies this globally
=> refactor(tile): update story, refactor styles

package.json, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap, src/components/__tests__/publicAPI.spec.js
- Sort components before creating snapshot to ignore reorganisation of exports
- Add `jest` script to allow individual file testing
=> test(public-api): sort components to ignore order

package.json
- Resolves #402 
- mark `carbon-components`, `carbon-components-react`, and `@carbon/*` elements packages as peer dependencies
=> feat(carbon): mark carbon core pkgs as peer dependencies

src/components/Accordion/__tests__/Accordion.spec.js
- removed unused import that was causing a linting error
=> chore(accordion): remove unused imported prefix

src/components/ScrollGradient/ScrollGradient.stories.js, src/components/ScrollGradient/_index.scss, src/components/TypeLayout/TypeLayout.stories.js
- Fix bug that a parent scroll gradient applies gradients on child scroll gradients.
- Check out the new story added for the ScrollGradient component
- Notice that the internal scroll gradient does not get its gradient activated by its parent
=> fix(scroll-gradient): apply scroll state styles to direct children only

src/components/Nav/Nav.js
Resolves #461
Use React method to facilitate `forEach` for `Nav` children
=> fix(nav): accommodate single child

.storybook/theme/index.js
- Resolves #458
(look at top left -- where there's the lockup image etc.)
- move lockup image to `brandName` and also include package info + name
- remove `brandImage` (because it visually overrides `brandName`)
Keep in mind that this is how Carbon's storybook looks (see top left): https://react.carbondesignsystem.com
How similar do we want to be?
Should we keep the lockup image?
Should the package name + version be written differently?
=> docs(storybook): update storybook sidebar with package info and version

src/globals/theme/_index.scss, src/globals/theme/_variables.scss
As per SCSS import tests, the proposes to move theme ignore list to variables for use across functions and mixins, and accommodate individual component imports
=> fix(theme): move ignore list to variables for use across partials

src/components/Breadcrumb/_index.scss
Workaround for https://github.com/carbon-design-system/carbon/pull/5916
Add reset to `Breadcrumb` to prevent browser defaults for containing `ol` when the CSS reset is toggled off
=> fix(breadcrumb): reset containing `ol` browser defaults

src/components/FilterPanel/__tests__/FilterPanel.spec.js
Current `FilterPanel` tests generate some noise due to unrecognized props --
```
PASS  src/components/FilterPanel/__tests__/FilterPanel.spec.js
● Console
console.error node_modules/react-dom/cjs/react-dom.development.js:530
Warning: React does not recognize the `MockFilterData` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `mockfilterdata` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in section (created by FilterPanel)
in FilterPanel
console.error node_modules/react-dom/cjs/react-dom.development.js:530
Warning: React does not recognize the `filtersExpandLabel` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as …
```
=> chore(filter-panel): prevent unrecognized props from generating warnings in tests

src/components/TagWall/TagWall.js, src/components/TagWall/__tests__/__snapshots__/TagWall.spec.js.snap, src/components/TagWall/_mixins.scss, src/components/TagWallFilter/Filter/Filter.js, src/components/TagWallFilter/Filter/__tests__/__snapshots__/Filter.spec.js.snap, src/components/TagWallFilter/Filter/_mixins.scss, src/components/TagWallFilter/TagWallFilter.stories.js, src/components/TagWallFilter/__tests__/__snapshots__/TagWallFilter.spec.js.snap, src/components/Tearsheet/TearsheetSmall/_mixins.scss
- Resolves #511 
- truncate tags in `TagWall` to 40ex per input from design
- truncate list items in `TagWall` to width of container
- update storybook demo to show what happens with long strings
- The `TagWall` demo has a long string now, so you can see how it appears when truncated. You can then remove the tag, returning it the list below, and see how it appears truncated in the list of options.
=> fix(tagwall): accommodate truncation in tags and list items

src/components/Tearsheet/Tearsheet.stories.js
When running the storybook environment locally, you will see the following console error for the `Tearsheet` story:
```
Warning: Failed prop type: The prop `id` is marked as required in `ForwardRef(TextInput)`, but its value is `undefined`.
in ForwardRef(TextInput) checkPropTypes.js:20
printWarning checkPropTypes.js:20
checkPropTypes checkPropTypes.js:82
React 2
js Tearsheet.stories.js:70
js main.8aa11d6e3dab039344c8.bundle.js:31055
Webpack 19
```
This PR resolves this by adding the missing `id` to the `TextInput` in the `Tearsheet` story.
- add `id` to `TextInput` in `Tearsheet` storybook demo
You need to run locally to see the error in development.
=> docs(tearsheet): add id to input in small tearsheet demo

src/components/Checkbox/_index.scss
- Resolves #517 
- Remove old style override that is no longer needed
- Overrides the `border-color` from Carbon to use `$interactive-04` (which is blue40 for dark themes) instead of `$focus` (which is white for dark themes & causing issues). Note that I'm also open to using `$interactive-01` here (blue60 for all themes), but blue40 seemed appropriate because it also matches the link color 🤔 
NOTE: rules here are necessary to override this code block https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/checkbox/_checkbox.scss#L148
=> fix(checkbox): override border color for focus state

src/components/RadioButton/RadioButton.stories.js
- remove `checked` prop knob, which was preventing the component from being interacted with in the storybook demo
=> docs(radio-button): remove checked knob from story so component is interactive

src/components/TypeLayout/_index.scss
Resolves #523
Use `ui-03` for `TypeLayout` border as per Carbon guidance - https://www.carbondesignsystem.com/guidelines/color/usage
=> fix(type-layout): use `ui-03` for subtle border

src/components/Tearsheet/Tearsheet.js, src/components/Tearsheet/Tearsheet.stories.js, src/components/Tearsheet/_mixins.scss, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
Resolves #483
Prevent rendering of the `Tearsheet` sidebar if the prop is not passed in
Use 'Sidebar' knob in any `Tearsheet` story
=> feat(tearsheet): add ability to remove sidebar

src/components/ComboButton/ComboButton.js, src/components/ComboButton/ComboButton.stories.js, src/components/ComboButton/__tests__/ComboButton.spec.js, src/components/ComboButton/__tests__/__snapshots__/ComboButton.spec.js.snap
Right now the tests & dev environment show warnings for the `ComboButton`'s keys -- specifically for keys generated for the inner `Button` and the inner `OverflowMenuItem`s.
This PR proposes using a unique value like `href` for the keys. Also, it allows consumer to provide a unique ID if they want, which will in turn be used for a key.
- allow `id`s for inner `Button` and inner `OverflowMenuItem`
- if `id` is provided, use that for the `key` -- otherwise, use the `href`
=> fix(combo-button): use id for keys, allow id attr, update stories

.storybook/addons/addon-theme/index.js, .storybook/addons/addon-theme/register.js
Right now in development, when viewing the storybook environment, you will see a large warning about a miss `key` value on the top level `Theme`:
- the component wrapper `Theme` will have a `key={NAME-OF-THEME}` (this is not the specific missing `key` being flagged but still seems useful, anyway)
- the `Theme` addon panel will have a `key` that matches naming convention of other addon panels -- e.g., `key="storybook/theme/panel"`
=> fix(storybook): add keys to theme components

src/components/Card/Card.js
- Resolves #542
- adds `...other` spread attribute, which would resolve requests like #542 by allowing consumers to pass in additional attributes, like `target="_blank"`
=> fix(card): add spread attribute to component wrapper

src/components/FilterPanel/FilterPanelAccordion/FilterPanelAccordion.js, src/components/FilterPanel/FilterPanelAccordionItem/FilterPanelAccordiontItem.js, src/components/FilterPanel/FilterPanelCheckbox/FilterPanelCheckbox.js, src/components/FilterPanel/FilterPanelCheckbox/FilterPanelCheckbox.stories.js, src/components/FilterPanel/FilterPanelCheckboxWithOverflowMenu/FilterPanelCheckboxWithOverflowMenu.stories.js, src/components/FilterPanel/FilterPanelGroup/FilterPanelGroup.js, src/components/FilterPanel/FilterPanelLabel/FilterPanelLabel.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
- Resolves #566
- Update the prop type for all of the filter panel subcomponents to allow strings for the `count` props
- Check out the Storybook story for the `FilterPanelCheckbox` and update the `count` prop knob to include a letter
=> feat(filter-panel): allow for string counts

package.json
Resolves #556
Remove `storybook-static` folder from package artifacts to reduce bundle size.
=> build(storybook): remove static assets from package

src/components/Tearsheet/Tearsheet.js, src/components/Tearsheet/__tests__/__snapshots__/Tearsheet.spec.js.snap, src/components/Wizard/Wizard.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
- Resolves #565
- add `className` prop and spread attribute to `Tearsheet`
- add `className` prop and spread attribute to `Wizard`
=> fix(wizard): add className prop and spread attribute

src/components/SearchBar/SearchBar.stories.js
- change mention of `sortOrder` to `sortItems`
=> docs(search-bar): update demo documentation for sortItems prop

src/components/TagWallFilter/__tests__/__snapshots__/TagWallFilter.spec.js.snap, src/components/Tearsheet/Tearsheet.js, src/components/Tearsheet/TearsheetSmall/TearsheetSmall.js, src/components/Tearsheet/TearsheetSmall/TearsheetSmall.stories.js, src/components/Tearsheet/TearsheetSmall/__tests__/__snapshots__/TearsheetSmall.spec.js.snap, src/components/Tearsheet/__tests__/__snapshots__/Tearsheet.spec.js.snap
- Resolves #601 
Similar approach as #576 -
- pass through `isLoading` with loading state so that it can be used to making interactive elements non-interactive while `TearsheetSmall` is loading
- provide guidance for using `isLoading`
- make sure that all `TearsheetSmall` buttons are set to `disabled={true}` whenever loading state is active, so that they cannot be tabbed to in the background
Cleanup:
- in the `Tearsheet`, replace usage of `tabIndex` with the `disabled` attribute to make elements non-interactive during loading state
=> fix(tearsheet-small): pass through isLoading, provide examples for making content non-interactive when loading

src/components/Wizard/Wizard.js
- Related to #617 but does not completely resolve it  
If you look at the `Wizard` right now and hover over almost any part of it, a default tooltip will appear with the title text. Right now the `title` prop is being leaked as a `title` attribute to the inner `Tearsheet`, which doesn't seem intended.
- destructured props in the same spot
- avoid leaking `title` prop to `title` attribute
=> fix(wizard): update prop destructuring and prevent title attr leaking

src/components/DataTable/DataTablePagination/DataTablePagination.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
- Part of #457 
- remove unused prop `itemsPerPageFollowsText` which doesn't do anything & also that causes console errors in test output, e.g.:
```
console.error node_modules/react-dom/cjs/react-dom-server.node.development.js:76
Warning: React does not recognize the `itemsPerPageFollowsText` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `itemsperpagefollowstext` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in div
in Pagination
in div
```
=> fix(data-table-pagination): remove unused prop itemsPerPageFollowsText

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/IconButtonBar/IconButtonBar.js, src/components/IconButtonBar/IconButtonBar.stories.js, src/components/IconButtonBar/__tests__/IconButtonBar.spec.js, src/components/IconButtonBar/__tests__/__snapshots__/IconButtonBar.spec.js.snap, src/components/IconButtonBar/_index.scss, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
- Resolves #568 
- add `divider` prop that renders a divider element on either side of an icon button, depending on prop value
- add storybook knobs/demo for new prop
- add tests for new prop
-
=> feat(icon-button-bar): add divider prop with demo and tests

src/components/DataDecorator/DataDecorator.js
- use `onClose` prop for inner `PanelV2` so that a panel opened with the `DataDecorator` can also be closed with the escape key or clicking outside the panel.
NOTE: not providing an `onClose` prop for this because the `DataDecorator` already has an existing `onClose` prop that does something slightly different.
=> fix(data-decorator): allow inner panel to be closed with esc key or outside click

src/components/DataDecorator/DataDecorator.js, src/components/DataDecorator/Decorator/Decorator.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
@jendowns the most important aspect of this is the ability to include the `onContextMenu` prop for the `DataDecorator` and `Decorator` components. The overriding of the `DataDecorator`'s `onClick` can be removed if its not desirable.
=> Expose (Data)Decorator onContextMenu prop

src/components/DataTable/DataTable.js, src/components/DataTable/DataTable.stories.js, src/components/DataTable/DataTablePagination/__tests__/__snapshots__/DataTablePagination.spec.js.snap, src/components/DataTable/__tests__/__snapshots__/DataTable.spec.js.snap, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
Related to #664
- Proxy Carbon's `DataTable` `defaultProps` and `propTypes` - any changes upstream were not being reflected and would cause disparities between both implementations and consumer expectation
- Update snapshots to reflect changes
- Add `size` knob to `DataTable` stories
=> fix(data-table): proxy `defaultProps` and `propTypes`

src/components/SearchBar/SearchBar.js, src/components/SearchBar/__tests__/__snapshots__/SearchBar.spec.js.snap
The `showIcon` prop passed to inner `Search` component is not a valid `Search` prop:
https://github.com/carbon-design-system/carbon/blob/f592f2d2540042befa0cc8e97cb31a0d9c52f748/packages/react/src/components/Search/Search.js#L18
- remove `showIcon` prop from `Search` component and update snapshots
=> fix(searchbar): remove unused Search prop showIcon

src/components/Tearsheet/TearsheetSmall/TearsheetSmall.js, src/components/Tearsheet/TearsheetSmall/TearsheetSmall.stories.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
- Resolves #601
- update uses of `body` and `isLoading` render prop so that you can't tab through `TearsheetSmall` content while it is loading.
- deprecate the `children` prop for `TearsheetSmall`, which is a "hidden" prop because it isn't documented in the storybook and isn't shown as part of that recommended API (alternatively I can be convinced to deprecate `body` instead -- it's just that `body` has been part of the API for some time, and it's demonstrated in the storybook... whereas `children` is only utilized, as far as I can tell, by the `TagWallFilter`. It's just that we shouldn't have both existing to do the same thing.)
- make sure you can't tab through `TearsheetSmall` content while it is loading
=> feat(tearsheet-small): update use of body prop and isLoading render prop, deprecate children prop

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/Card/_mixins.scss
- Resolves #677
- remove `text-transform: capitalize` style from `Card` header text
=> fix(card): remove text-transform capitalization from header

src/components/ComboButton/ComboButton.js, src/components/ComboButton/ComboButton.stories.js, src/components/ComboButton/ComboButtonItem/ComboButtonItem.js, src/components/ComboButton/__tests__/__snapshots__/ComboButton.spec.js.snap, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
- partially addresses #683 
- deprecate `primaryFocus` prop
- replace with `selectorPrimaryFocus`
=> feat(combo-button): deprecate primaryFocus prop, replace with selectorPrimaryFocus

src/components/IconButtonBar/IconButtonBar.js, src/components/IconButtonBar/IconButtonBar.stories.js, src/components/IconButtonBar/__tests__/__snapshots__/IconButtonBar.spec.js.snap, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
partially addresses #683 
- use `selectorPrimaryFocus` in `OverflowMenu` (set it to a known class name for icon buttons)
- add `setFocus` prop to individual actions (assign it a class name if true)
- ensure that `IconButtonBar` functions as expected
=> fix(icon-button-bar): use selectorPrimaryFocus in OverflowMenu

src/components/DataTable/stories/with-overflow-menu.js, src/components/OverflowMenu/OverflowMenu.stories.js
- Resolves #683 
- remove usage of old prop `primaryFocus` from `OverflowMenu` story
- remove usage of old prop `primaryFocus` from `DataTable` with overflow menu story
=> docs(overflow-menu): remove usage of primaryFocus in stories

src/components/Toolbar/Toolbar.js, src/components/Toolbar/__tests__/__snapshots__/Toolbar.spec.js.snap
- Resolves #696
- ensure that toolbar `aside` has valid `id`
- add `aria-expanded` boolean to toolbar buttons
- conditionally add `aria-control` to toolbar button if corresponding `aside` is opened
=> fix(toolbar): ensure that toolbar panels have ids, update aria attributes

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/Header/Header.js, src/components/Header/_mixins.scss, src/components/Header/_mocks_/index.js, src/components/Header/constants.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
- Resolves #668
I have opted to add the extra section below the profile popover heading, and above the body section. But let me know if it needs to be moved.
- adds `profile.description` prop with `node` type
- update stories to include the prop in use
- update snapshots
=> feat(header): add profile.description prop to the popover

src/components/OverflowMenu/_index.scss
Add CSS helpers to `OverflowMenu` styles to accommodate `visually-hidden` dependency when importing the component in isolation (see https://deploy-preview-47--ibm-cloud-paks.netlify.app/?path=/story/security-iconbuttonbar--default and select `OverflowMenu`)
=> fix(overflow-menu): add `visually-hidden` dependency

src/components/Header/Header.js, src/components/Panel/PanelContainer.js
- Resolves #717
- Removes `footer` element from `Header` component notifications popover, since the content there is not contained within a specific sectioning element + the content is not particularly ["footer-like" according to the spec](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-footer-element.html).
- double-check that the `Header` component's notification popover still looks good 👍
=> fix(header): remove footer element from popover

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/Wizard/Wizard.js, src/components/Wizard/Wizard.stories.js, src/components/Wizard/_index.scss
- Resolves #617
- fix issue where `.security--wizard` className was being dropped
- update styles for vertical `ProgressIndicator` in `Wizard` to hide the line and remove some margins
- allow `Wizard` steps to be 3 lines long / 40 characters before truncating them (this can be updated to whatever)
- review the `Wizard` story
=> fix(wizard): fix className, allow 3 lines for steps before truncation

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/SearchBar/SearchBar.js, src/components/SearchBar/SearchBar.stories.js, src/components/SearchBar/__tests__/__snapshots__/SearchBar.spec.js.snap, src/components/SearchBar/_index.scss, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
- Resolves #722 
- add `titleText` prop to provide label for inner `MultiSelect` (the generated `<label>` element is then tied to ARIA attributes in generated markup)
- add `hideScopesLabel` boolean prop to allow you to visually hide the generated `MultiSelect` label while still maintaining the ARIA attributes. NOTE: set to `true` by default for compatibility with existing implementations in product.
- pull down branch and experiment with turning `hideScopesLabel` on/off, inspect the ARIA attributes, etc.
=> feat(search-bar): apply titleText prop for inner multiselect

src/components/ScrollGradient/ScrollGradient.js
`resize-observer-polyfill` already checks for the native implementation of `ResizeObserver`, so this change enables it to handle that for us instead
=> fix(resize-observer): allow library handle ponyfill

src/components/Nav/NavItem/NavItem.js, src/components/Nav/NavItem/__tests__/NavItem.spec.js, src/components/Nav/NavItem/__tests__/__snapshots__/NavItem.spec.js.snap, src/components/Nav/NavList/__tests__/__snapshots__/NavList.spec.js.snap, src/components/Nav/__tests__/__snapshots__/Nav.spec.js.snap
- Add `tabindex` to link `NavItemLink` to prevent tabbing while `NavList` is open
- Remove `tabindex` unit test as the `NavItem` should always have `children`
- Update snapshot tests
=> fix(nav-item): add `tabindex` to link

src/components/ICA/ICA.js, src/components/ICA/ICA.stories.js, src/components/ICA/__tests__/ICA.spec.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
Resolves #743 
Add `truncate` prop to ICA to support displaying non-formatted values
=> feat(ica): add `truncate` prop

src/components/Wizard/Wizard.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
- Resolves #737
- adds `navLabel` prop with a default value "Steps navigation", to provide an accessible label to the inner `Nav` component. "Steps navigation" versus "Wizard navigation" because "Wizard" is more of a UI dev/design term, and this label is meant to be understood by users.
- verify the nav markup has a valid `aria-label` attribute in the "Editable Wizard" variation: https://deploy-preview-738--ibm-security.netlify.app/?path=/story/patterns-wizard--with-editable-wizard
=> feat(wizard): add prop to provide accessible label to nav

src/components/SummaryCard/SummaryCardSkeleton/SummaryCardSkeleton.js, src/components/SummaryCard/SummaryCardSkeleton/__tests__/SummaryCardSkeleton.spec.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
Resolves #760 
Add `className` and optional props to `SummaryCardSkeleton`
=> feat(summary-card-skeleton): add `className`, spread props

src/components/Nav/NavItem/NavItem.js, src/components/Nav/NavItem/__tests__/__snapshots__/NavItem.spec.js.snap, src/components/Nav/NavList/__tests__/__snapshots__/NavList.spec.js.snap, src/components/Nav/__tests__/__snapshots__/Nav.spec.js.snap, src/components/Toolbar/Toolbar.js, src/components/Toolbar/_mocks_/index.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
Resolves #710
- Add support for supplying IDs to toolbar navigation items
- Generate `NavItem` instance ID if none is supplied
- Refactor `Toolbar` mocks to be more flexible with props
- Update snapshot tests
=> feat(toolbar): support supplying IDs to navigation items

src/components/StatusIcon/StatusIcon.js, src/components/StatusIcon/StatusIcon.stories.js, src/components/StatusIcon/__tests__/StatusIcon.spec.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
- Resolves #764 
- adds an aria label to the icon to allow for status accessibility 
https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html
- check preview knob and inspect the element
=> fix(StatusIcon): add aria label to icons

src/components/Toolbar/Toolbar.js
Add default value for `Toolbar` `mainNavigation` and `ariaLabel` as otherwise causes rendering to crash
=> fix(toolbar): add default values for compatibility

package.json, src/components/Nav/Nav.js, src/components/Nav/Nav.stories.js, src/components/Nav/NavList/NavList.js, src/components/Toolbar/Toolbar.js, src/components/Toolbar/_mocks_/index.js
Resolves #784
- Call `onClick` handlers for `NavItem`s generated in `Nav` and `NavList`
- Pass-through props for `Toolbar` to support `onClick` handlers
- Update stories to reflect changes
=> fix(nav): correctly apply `onClick` handlers, spread `Toolbar` props

src/components/DataDecorator/DataDecorator.js, src/components/DataDecorator/Decorator/Decorator.stories.js, src/components/DataDecorator/Decorator/__tests__/Decorator.spec.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
Resolves #800 
- Expose `focusTrapOptions` prop to `DataDecorator` to pass-through to `PanelV2` and subsequently `Portal`
- Reorder `DataDecorator` imports and props
=> feat(data-decorator): pass through `focusTrapOptions`

src/components/Toolbar/Toolbar.js
https://jsw.ibm.com/browse/SECCON-4160
- Resolves https://jsw.ibm.com/browse/SECCON-4160
Add onClick handler to navItems so the toolbar closes when item is cl
Click on a navItem and make sure toolbar closes
=> Add onClick handler to navItems so the toolbar closes when item is clicked

src/components/UNSTABLE__LayoutModules/ActionBarModule/index.mdx, src/components/UNSTABLE__LayoutModules/ButtonClusterModule/index.mdx, src/components/UNSTABLE__LayoutModules/CardModule/index.mdx, src/components/UNSTABLE__LayoutModules/DescriptionListModule/index.mdx, src/components/UNSTABLE__LayoutModules/DescriptionModule/index.mdx, src/components/UNSTABLE__LayoutModules/ICAModule/index.mdx, src/components/UNSTABLE__LayoutModules/TitleBarModule/index.mdx
Reorder contents of documentation to:
1. Overview
2. API
3. Anatomy
4. Variants/Interactions
5. ...
=> docs(layout-modules): reorder documentation contents

src/components/Toolbar/Toolbar.js
- Resolves #705 
- Pass `element` prop from `Toolbar` props down to the `NavItem` component.
- Verified by modifying `Toolbar` mock data to include an `element` prop and inspecting the rendered HTML in Storybook. Did not update mocks but can if required.
=> feat: add NavItem element support for Toolbar

src/components/ComboButton/ComboButton.js, src/components/ComboButton/__tests__/__snapshots__/ComboButton.spec.js.snap
```
Warning: ComboButtonItem: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)
at ComboButton
```
This might cause developers looking for errors on their side when they use the `ComboButton`.
- Don't use a loop for the single button
- Don't try to access `key` from the prop
- Run storybook in dev mode (using `yarn start`) and verify there is no more warning
- Verify `ComboButton` still works as exepected
=> fix(combo-button): key is not a prop warning

src/components/ComboButton/ComboButton.js, src/components/ComboButton/ComboButton.stories.js, src/components/ComboButton/__tests__/ComboButton.spec.js, src/components/ComboButton/__tests__/__snapshots__/ComboButton.spec.js.snap
- Resolves #845 
- Spread `{...buttonProps}` onto the primary action button. This gives consumers the added flexibility to add props for the underlying `Button` element such as `target="_blank"` which for example provides the ability to open primary action links in a new tab.
- Migrated `ComboButton.spec.js` unit tests to using `react-testing-library` and added accessibility tests
- I have added the extra prop `target="_blank"` to the primary action item in `ComboButton.stories.js`. This link should now open in a new tab.
- I have also added an extra `ComboButtonItem` component to `ComboButton.stories.js` which exemplifies the use case of opening a link in a new tab. I think this offers greater visibility for consumers.
=> feat(combo-button): add prop spreading to primary action button

src/components/Toolbar/Toolbar.js, src/components/Toolbar/_mocks_/index.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
Changed toolbar title from prop type string to node so we can have a title as well as a component.
- Resolves  SECCON-9522
- Change title string to node
- Updated storybook mocks also
=> feat(toolbar): enable nodes in titles

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/PanelV2/_mixins.scss
Current panelV2 footer position is set to `fixed`. This would create another stacking context within footer.
This might cause footer overflow menu has lower `z-index` than other element in panel context.
See below screenshot :
=> fix(PanelV2): change footer position from fixed to absolute

src/components/TruncatedList/TruncatedList.js, src/globals/namespace/index.js
- `carbon-components` JavaScript ends up entirely in the application bundle
- change require to import syntax for `carbon-components` to allow treeshaking again
- check the snapshot tests to make sure the same prefix is still applied
=> fix: change require to import syntax for `carbon-components` to allow treeshaking again

README.md
Fix README copy and update npm guidance - [`-S` is no longer needed by npm](https://docs.npmjs.com/cli/v7/commands/npm-install)
=> docs(README): fix copy, update npm guidance

src/components/Nav/Nav.js
Contributes to #973
Fix `Nav` test warnings by evaluating against `NavList`s name instead of an empty instance of it, so the test output no longer throws `propType` errors
=> refactor(nav): fix test warning

src/components/Tearsheet/TearsheetSmall/TearsheetSmall.js, src/components/__tests__/__snapshots__/publicAPI-test.js.snap
Contributes to #973 
To prepare for Cloud & Cognitive compatibility, undeprecate `children` prop to suppress the warning in the test output without having to rewrite the test suite.
=> feat(tearsheet-small): undeprecate `children` prop

src/__tests__/scss/styles-test.js
- Resolves https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/918/checks#step:7:1114
Make styles test entry point relative to the current directory as the `root` variable will vary between repos. In `ibm-security` it's `__dirname`, but in `ibm-cloud-cognitive`, as it's a monorepo, it's `${__dirname}/../..`
=> test(styles): fix file reference

src/globals/deprecate/index.js
- Resolves eslint finding
- Align function and jsdoc param name
-
=> chore(globals): fix jsdoc params in deprecate util

src/components/Nav/Nav.js, src/components/Nav/NavItem/NavItem.js, src/components/Nav/NavItem/__tests__/NavItem-test.js, src/components/Nav/NavList/__tests__/__snapshots__/NavList-test.js.snap, src/components/Nav/__tests__/__snapshots__/Nav-test.js.snap, src/components/__tests__/__snapshots__/publicAPI-test.js.snap
- Nav: mark `activeHref` as throw away
- NavItem:
- remove unused `onKeyPress`
- mark `current` as throw away
-
=> fix(nav-item): remove unused prop `onKeyPress`

src/components/Header/Header.js, src/components/Header/HeaderListItem/HeaderListItem.js, src/components/Header/HeaderListItem/__tests__/HeaderListItem-test.js, src/components/Header/HeaderListItem/constants.js, src/components/Header/__tests__/__snapshots__/Header-test.js.snap
- `aria-expanded` and `aria-haspopup` are not valid on `li` (role `listitem`)
- Move the two attributes to the buttons that have this characteristic.
- Clean up the `children` prop.
-
=> fix(header): set aria-expanded and aria-haspopup on the appropriate element

src/__tests__/scss/__snapshots__/styles-test.js.snap, src/components/DataDecorator/_mixins.scss
Resolves https://ibm-casdesign.slack.com/archives/C02AMK63SUD/p1631526628000400
Include `Decorator` icon styles removed as part of refactor
=> fix(decorator): fix icon `fill` styles

.storybook/index.scss
Suppress Sass warning when starting Storybook
=> docs: suppress Sass warning in Storybook

.storybook/index.js, src/components/LayoutModules/docs/examples/Detail/index.mdx, src/components/LayoutModules/docs/examples/Overview/index.mdx
Contributes to #973 
Align 'Layouts' category naming with Cloud & Cognitive per https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/packages/core/story-structure.js#L149
=> docs: align 'Layouts' naming with Cloud & Cognitive
