src/components/TypeLayout/_mixins.scss
- Resolves #27 
- set xs and sm font sizes to `caption-01` (12px)
=> fix(type-layout): set xs and sm font sizes to caption-01

src/components/ComboBox/ComboBox.stories.js
- update storybook import to follow convention
=> chore(combo-box): update component import in story

src/components/ExternalLink/ExternalLink.stories.js, src/components/ICA/ICA.stories.js, src/components/ICA/ICASkeleton/ICASkeleton.stories.js
- Resolves #51
- update `@storybook/addon-centered` usage in 3 stories
=> docs: update storybook/addon-centered usage in 3 stories

src/components/DataDecorator/__tests__/__snapshots__/DataDecorator.spec.js.snap, src/components/Icon/Icon.js, src/components/Icon/__tests__/__snapshots__/Icon.spec.js.snap, src/components/Nav/NavList/__tests__/__snapshots__/NavList.spec.js.snap, src/components/Nav/__tests__/__snapshots__/Nav.spec.js.snap, src/components/TagWall/__tests__/__snapshots__/TagWall.spec.js.snap, src/components/TagWallFilter/__tests__/__snapshots__/TagWallFilter.spec.js.snap
- Fix `Icon` prop warning for `aria-hidden`
=> fix(icon): fix prop warning

src/components/Header/HeaderNotification/_mixins.scss
- `cherry-pick` color contrast fix
=> fix(notifications): `cherry-pick` color contrast fix

.github/ISSUE_TEMPLATE/BUG.md, README.md
- Add CodeSandbox template to README and issue template
=> docs(codesandbox): add basic CodeSandbox example for debugging

src/components/Wizard/WizardStep.js
- Resolves #64 
- Add detail for `Wizard` `validate` prop
=> docs(wizard): add detail for `validate` prop

src/components/Tearsheet/_mixins.scss
- Resolves #74
- Fix `Tearsheet` toggle animation
=> fix(tearsheet): fix toggle animation

src/components/Button/Button.js, src/components/Button/Button.stories.js, src/components/Button/_mixins.scss, src/components/Tearsheet/Tearsheet.js, src/components/Tearsheet/_mixins.scss
- Resolves #19 
- Adds 'ghost-danger' option to Button component
- Removes current ghost danger implementation from Tearsheet and uses the one implemented on Button
=> feat(button): add ghost danger button

README.md
- Resolves #14 
* added link to Carbon Developer Essentials in README
=> docs(tutorial): add link to tutorial

src/components/StringFormatter/StringFormatter.js, src/components/StringFormatter/StringFormatter.stories.js, src/components/StringFormatter/__tests__/StringFormatter.spec.js, src/components/StringFormatter/__tests__/__snapshots__/StringFormatter.spec.js.snap, src/components/StringFormatter/_index.scss, src/components/StringFormatter/_mocks_/index.js
- Enables mutli line clamping for string formatter
[Note on `line-clamp` and its browser support](https://caniuse.com/#search=line-clamp) - how does this align to this library?
=> feat(stringformatter): enable multiline clamping

CODEOWNERS
- Add reviewers automatically and link to documentation
=> chore(CODEOWNERS): add reviewers automatically

.storybook/components/Container/_index.scss, .storybook/index.scss, src/components/TagWallFilter/TagWallFilter.js, src/components/TagWallFilter/__tests__/__snapshots__/TagWallFilter.spec.js.snap, src/components/Tearsheet/TearsheetSmall/TearsheetSmall.js, src/components/Tearsheet/TearsheetSmall/TearsheetSmall.stories.js, src/components/Tearsheet/TearsheetSmall/__tests__/__snapshots__/TearsheetSmall.spec.js.snap, src/components/Tearsheet/TearsheetSmall/_mixins.scss
- Resolves #118 
- Add `flush` modifier to `TearsheetSmall`
- Update snapshot tests
- Remove unused Storybook styles
=> feat(tearsheet-small): add flush modifier, remove redundant code

src/components/Pill/Pill.stories.js
- adjust template string in story source for the `Pill` component
=> docs(pill): adjust template string in story source

src/components/DataDecorator/_index.scss, src/components/DataDecorator/_mixins.scss, src/components/DelimitedList/_index.scss, src/components/DelimitedList/_mixins.scss, src/components/ErrorPage/_index.scss, src/components/ErrorPage/_mixins.scss, src/components/Pagination/_index.scss, src/components/ScrollGradient/_index.scss, src/components/ScrollGradient/_mixins.scss, src/components/SearchBar/_index.scss, src/components/SearchBar/_mixins.scss, src/components/SkeletonText/_index.scss, src/components/SkeletonText/_mixins.scss, src/components/TagWall/_index.scss, src/components/TagWall/_mixins.scss, src/components/TagWallFilter/_index.scss, src/components/TagWallFilter/_mixins.scss, src/components/TextArea/_index.scss, src/components/TimePicker/_index.scss, src/components/TooltipDefinition/_index.scss, src/components/TypeLayout/_index.scss, src/components/Wizard/_mixins.scss
- update sass doc groups & comments for consistency
=> chore(styles): update sass doc group & file comments for consistency

src/components/StatusIcon/_mixins.scss
- Resolves #192 
- Align complete and default status icon sizes
=> fix(status-icon): align status icon size

CODEOWNERS
- Update CODEOWNERS to reflect new team structure (design and development)
=> docs(CODEOWNERS): update CODEOWNERS to reflect team structure

src/components/Accordion/Accordion.js
- Resolves #211
- Remove align prop from `CarbonAccordion`
=> fix(accordion): remove align prop from `CarbonAccordion`

src/components/Toolbar/_mixins.scss
- Resolves #214 
- Define order for toolbar and panel layer based on header `z-index`
=> fix(toolbar): negotiate `z-index`

src/components/DatePicker/DatePicker.stories.js
- Resolves #216 
- Fix `DatePicker` single calendar story
- Refactor story imports and extra information
=> docs(date-picker): fix single calendar story, refactor imports

src/components/StepIndicator/_mixins.scss
- Resolves #215 
- Transform complete step
- Refactor styles based on public Carbon and remove `1.x` overrides
=> fix(step-indicator): refactor styles, transform completed step

src/components/Header/Header.js, src/components/Header/__tests__/__snapshots__/Header.spec.js.snap, src/components/Header/_mixins.scss, src/components/Header/constants.js, src/components/Header/locales/en/Header.json
- Resolves #202 
- Add optional `domain` brand prop to allow for correct wordmark font weights
=> feat(header): add optional `domain` brand prop

src/globals/theme/_index.scss
- Add support for legacy theme initialisation
=> fix(theme): add support for legacy theme initialisation

src/components/DataTable/_index.scss, src/components/DataTable/stories/with-overflow-menu.js
- Resolves #189
- Fix theme tokens and reduce overrides
- Update overflow menu example to use correct props
=> fix(data-table): fix theme tokens, reduce overrides

docs/migration/migrate-to-2.x.md, src/components/Card/__tests__/Card.spec.js, src/components/Card/index.js, src/components/Card/migrate-to-2.x.md, src/index.js
BREAKING CHANGE: `Card` export has been updated to align with other components.
- Resolves #254
- Update `Card` export to align with other components
=> refactor(card): update export to align with other components

docs/migration/migrate-to-2.x.md, src/components/Notification/ToastNotification/_index.scss, src/components/Notification/_index.scss, src/components/Notification/migrate-to-2.x.md, src/components/StackedNotification/_index.scss
BREAKING CHANGE: `ToastNotification` style export has been updated to align with other components.
- Resolves #256
- Update `ToastNotification` style export to align with other components.
=> refactor(toast-notification): update style export to align with other components

README.md
- Resolves #303 
- update CodeSandbox link to use instance with updated version of the library
=> docs(readme): update codesandbox link

src/components/Tearsheet/TearsheetSmall/_mixins.scss
Resolves #354 
Allows small tearsheet text to break
=> fix(tearsheet): allow text reflow

src/globals/_index.scss
Resolves https://github.com/carbon-design-system/ibm-security/pull/241#pullrequestreview-367401980
Revert global theme ordering to ensure theme tokens are configured
=> fix(theme): revert global order

src/components/DatePicker/_index.scss
Resolves https://github.com/carbon-design-system/ibm-security/pull/241#pullrequestreview-367401980
Revert required `DatePicker` styles for theming
=> fix(date-picker): revert styles

package.json, src/components/StatusIndicator/StatusStep/__tests__/StatusStep.spec.js
- update browserslist
- remove compat eslint comment in `StatusStep` tests
NOTE: let me know if you disagree about doing this in a chore. 🤔
=> chore(lint): update browserslist and remove compat comment

src/globals/_index.scss
Fix order of imports to prevent reset from being outputted as intended
=> fix(reset): ensure reset is not compiled in output CSS

src/components/Nav/NavItem/NavItem.js
Resolves #473 
Remove `NavList` active state if the link is external
=> fix(nav-item): remove active state for external links

src/components/ComboBox/_index.scss, src/components/DatePicker/_index.scss, src/components/FilterPanel/FilterPanelAccordionItem/_mixins.scss, src/components/FilterPanel/FilterSearch/_index.scss, src/components/Tag/InteractiveTag/_mixins.scss, src/components/Tearsheet/TearsheetSmall/_mixins.scss, src/components/TruncatedList/_index.scss
Fix broken SCSS imports as surfaced by `test:scss` script
=> fix(scss): fix broken imports

src/components/DatePicker/_index.scss
Resolves #524
Add tokens to `DatePicker` styles to accommodate 'cool gray 10' and 'gray 100' themes
=> fix(date-picker): update hardcoded color values to tokens

src/components/Select/Select.stories.js
=> docs(select): fix story file comment

package.json, src/components/Header/_mixins.scss
Reintroducing height inheritance to accommodate breadcrumb shadow
=> fix(header): inherit height to accommodate breadcrumb shadow

src/components/DataTable/DataTable.js
Resolves #569
Pass through and render additional props for `DataTable` to render correct styles for the sorting varation
=> fix(data-table): fix sorting styles

.github/ISSUE_TEMPLATE/CARBON.md
Add issue template for upgrading Carbon
=> docs(carbon): add issue template

.achecker.yml
- Update a11y test policy
- Add link to configuration
- Prettier formatting
=> chore(a11y): update configuration

src/components/DataTable/stories/with-skeleton.js
Remove `rows` prop from `DataTableSkeleton` story
=> docs(data-table): update skeleton story

README.md
Include `experimental` branch as part of dist tag guidance
=> docs(dist-tags): update distribution guidance

src/components/DataTable/DataTable.stories.js
Resolves #612 
Update `DataTable` documentation URL
=> docs(data-table): update URL

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/Loading/_index.scss
Resolves #519
Override `Loading` overlay background color token to accommodate https://github.com/carbon-design-system/carbon/pull/6323
=> fix(loading-message): update background color token

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/SummaryCard/_mixins.scss
Resolves #633
Add `z-index` to `SummaryCardFooter` to prevent `z-index` from leaking out
=> fix(summary-card): prevent `z-index` leak

src/components/Tearsheet/Tearsheet.stories.js, src/components/Tearsheet/TearsheetSmall/TearsheetSmall.stories.js, src/components/Tearsheet/stories/index.js
Resolves #555
Add guidance for tearsheet animation
=> docs(tearsheet): add animation guidance

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/TagWallFilter/TagWallFilter.js, src/components/TagWallFilter/__tests__/__snapshots__/TagWallFilter.spec.js.snap, src/components/TagWallFilter/_index.scss, src/components/TagWallFilter/_mixins.scss, src/components/Tearsheet/TearsheetSmall/_index.scss, src/components/Tearsheet/TearsheetSmall/_variables.scss
Resolves #625
- Fix scrollbar alignment for `TagWallFilter` description
- Reorder `TagWallFilter` imports
=> fix(tag-wall-filter): fix scrollbar position

.storybook/index.scss
Add prefix for Storybook styles
=> docs(storybook): add missing style import

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/FilterPanel/FilterPanelAccordion/_index.scss, src/components/FilterPanel/FilterPanelAccordionItem/_index.scss, src/components/FilterPanel/FilterPanelCheckbox/_index.scss, src/components/FilterPanel/FilterPanelCheckboxWithOverflowMenu/_index.scss, src/components/FilterPanel/FilterPanelSearch/_index.scss, src/components/FilterPanel/LEGACY_FilterPanel/FilterSearch/_index.scss, src/components/FilterPanel/LEGACY_FilterPanel/FilterSubcategory/_index.scss, src/components/TruncatedList/_index.scss
Add correct `FilterPanel` component and subcomponent dependencies to enable import in isolation without styles breaking
=> fix(filter-panel): add correct dependencies for isolated import

README.md
Resolves #641
Update URL to working CodeSandbox with the latest version of `@carbon/ibm-security`
=> docs(codesandbox): update URL to fixed CodeSandbox

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/Dropdown/_index.scss, src/components/ListBox/_index.scss, src/components/_index.scss
Resolves #658 
- Add `ListBox` style import
- Add `ListBox` style as dependency for `Dropdown`
- Remove override resolved in Carbon upgrade
=> fix(dropdown): add `ListBox` styles

src/components/TruncatedList/_index.scss
Include `ScrollGradient` styles for use in isolation
=> fix(truncated-list): include `ScrollGradient` styles

src/components/Icon/Icon.stories.js
Resolves #681
- Wrap `Icon` story in `Fragment`
- Consolidate imports
=> docs(icon): wrap story in `Fragment`

package.json, src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/ScrollGradient/_index.scss
Resolves https://github.com/carbon-design-system/ibm-cloud-paks/pull/25#pullrequestreview-452938194
Add transition properties to `ScrollGradient` opacity
=> fix(scroll-gradient): add opacity transition properties

src/components/SummaryCard/_index.scss
=> fix(SummaryCard): import SkeletonText styles

src/components/ComboButton/ComboButton.js, src/components/ComboButton/__tests__/__snapshots__/ComboButton.spec.js.snap, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
- Resolves #720
- add `menuOffset` prop with default, apply to inner `OverflowMenu`
- add `menuOffsetFlip` prop with default, apply to inner `OverflowMenu`
=> feat(combo-button): add menuOffset and menuOffsetFlip props for inner OverflowMenu

package.json, src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/TagWallFilter/Filter/Filter.js, src/components/TagWallFilter/Filter/_mixins.scss, src/components/TagWallFilter/_mixins.scss, src/components/Tearsheet/_mixins.scss
Resolves #702
- Fix `TagWallFilter` input positioning
- Refactor imports
=> fix(tag-wall-filter): fix input positioning

.circleci/config.yml
Update Node.js version in CircleCI configuration
=> ci(node): update node version in configuration

src/components/Toolbar/Toolbar.js, src/components/Toolbar/__tests__/__snapshots__/Toolbar.spec.js.snap, src/components/Toolbar/locales/en/Toolbar.json, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap
Resolves #711
- Update `Toolbar` panel to remove role and use of `aside`
- Update snapshot
=> fix(toolbar): update panel semantics

package.json, src/components/Header/Header.js, src/components/Header/HeaderPopoverHeader/HeaderPopoverHeader.js
Resolves #716
Add `aria-labelledby` attributes for `Header` popover
=>  fix(header): add popover a11y attributes

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/UNSTABLE__LayoutModules/ButtonClusterModule/ButtonClusterModule.stories.js, src/components/UNSTABLE__LayoutModules/ButtonClusterModule/_index.scss, src/components/UNSTABLE__LayoutModules/ButtonClusterModule/index.js, src/components/UNSTABLE__LayoutModules/_index.scss, src/components/UNSTABLE__LayoutModules/index.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap, src/index.js
Add `ButtonClusterModule` layout module and sub-components and Storybook stories
=> feat(layout-modules): add button cluster module

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/UNSTABLE__LayoutModules/TitleBarModule/TitleBarModule.stories.js, src/components/UNSTABLE__LayoutModules/TitleBarModule/_index.scss, src/components/UNSTABLE__LayoutModules/TitleBarModule/index.js, src/components/UNSTABLE__LayoutModules/_index.scss, src/components/UNSTABLE__LayoutModules/index.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap, src/index.js
Add `TitleBarModule` layout module and Storybook stories
=> feat(layout-modules): add `TitleBarModule` and stories

.storybook/components/Background/_index.scss, .storybook/components/Background/index.js, .storybook/index.scss, src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/UNSTABLE__LayoutModules/CardModule/CardModule.stories.js, src/components/UNSTABLE__LayoutModules/CardModule/_index.scss, src/components/UNSTABLE__LayoutModules/CardModule/index.js, src/components/UNSTABLE__LayoutModules/_index.scss, src/components/UNSTABLE__LayoutModules/index.js, src/components/__tests__/__snapshots__/publicAPI.spec.js.snap, src/index.js
- Add Storybook background helper
- Add `CardModule` and stories
=> feat(layout-modules): add `CardModule`, Storybook background helper

.github/stale.yml
Add empty 'Stale' configuration file to trigger usage in the repo - https://github.com/probot/stale#usage
=> build(stale): add empty file for default configuration

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/Header/_variables.scss, src/components/Panel/_mixins.scss, src/components/PanelV2/_mixins.scss
Resolves #834 
Update `Header` and `Panel` `z-index` values to resolve changes introduced by Carbon - https://github.com/carbon-design-system/carbon/blame/master/packages/components/src/globals/scss/_layout.scss#L16
=> fix: update header and panel `z-index` values

.storybook/manager.js, .storybook/preview.js
Update location of analytics configuration as it wasn't getting initialized, as per https://github.com/storybookjs/storybook/issues/9727
=> build(analytics): fix analytics property

src/components/UNSTABLE__LayoutModules/DescriptionListModule/__tests__/DescriptionListModule.spec.js
Add `DescriptionListModule` unit tests
=> test(description-list-module): add unit test

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/Portal/_mixins.scss, src/components/Tearsheet/_mixins.scss
Update `Tooltip` `z-index` when inside `Portal`, similar to https://github.com/carbon-design-system/carbon/pull/6757
=> fix(portal): Update `Tooltip` `z-index` inside `Portal`

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/Loading/LoadingMessage/LoadingMessage.js, src/components/Loading/LoadingMessage/_index.scss, src/components/Loading/_index.scss
Remove `Loading` overrides and adjust spacing based on https://github.com/carbon-design-system/carbon/pull/7447
=> fix(loading): remove override

package.json, src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/Loading/LoadingMessage/LoadingMessage.js, src/components/Loading/LoadingMessage/_index.scss, src/components/Loading/_index.scss
=> chore: publish `v.1.38.1`

src/components/UNSTABLE__LayoutModules/ActionBarModule/ActionBarModule.stories.js, src/components/UNSTABLE__LayoutModules/ButtonClusterModule/ButtonClusterModule.stories.js, src/components/UNSTABLE__LayoutModules/CardModule/CardModule.stories.js, src/components/UNSTABLE__LayoutModules/DescriptionListModule/DescriptionListModule.stories.js, src/components/UNSTABLE__LayoutModules/DescriptionModule/DescriptionModule.stories.js, src/components/UNSTABLE__LayoutModules/ICAModule/ICAModule.stories.js, src/components/UNSTABLE__LayoutModules/PageTabModule/PageTabModule.ignore.js, src/components/UNSTABLE__LayoutModules/TitleBarModule/TitleBarModule.stories.js, src/components/UNSTABLE__LayoutModules/stories/Overview.stories.mdx, src/components/UNSTABLE__LayoutModules/stories/index.js
Add layout module 'Overview' section skeleton
=> docs(layout-modules): add `Overview` section skeleton

.storybook/index.js, .storybook/preview.js, src/components/StepIndicator/StepIndicator.stories.js, src/components/UNSTABLE__LayoutModules/ActionBarModule/index.mdx, src/components/UNSTABLE__LayoutModules/ButtonClusterModule/index.mdx, src/components/UNSTABLE__LayoutModules/CardModule/index.mdx, src/components/UNSTABLE__LayoutModules/DescriptionListModule/index.mdx, src/components/UNSTABLE__LayoutModules/DescriptionModule/index.mdx, src/components/UNSTABLE__LayoutModules/ICAModule/index.mdx, src/components/UNSTABLE__LayoutModules/PageTabModule/index.mdx, src/components/UNSTABLE__LayoutModules/TitleBarModule/index.mdx, src/components/UNSTABLE__LayoutModules/docs/examples/Detail/index.mdx, src/components/UNSTABLE__LayoutModules/docs/examples/Overview/index.mdx, src/components/UNSTABLE__LayoutModules/stories/Overview.stories.mdx, src/components/UNSTABLE__LayoutModules/stories/index.js, src/components/UNSTABLE__PageLayouts/Detail.stories.js, src/components/UNSTABLE__PageLayouts/Overview.stories.js, src/components/UNSTABLE__PageLayouts/stories/index.js
Resolves https://github.ibm.com/security/design-core-experience/issues/256
- Update information architecture to reflect the design
- Split out page layouts and use a shared configuration
=> docs(information-architecture): update navigation

.achecker.yml, src/components/TypeLayout/TypeLayout.js, src/components/TypeLayout/__tests__/TypeLayout.spec.js
Resolves #944 
Add correct roles and `tabindex` to `TypeLayout` to address accessibility test failure
=> fix(type-layout): address accessibility issues

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/DataTable/_index.scss
Resolves #956 
Fix `DataTable` styles import order
=> fix(data-table): fix styles import order

src/__tests__/scss/__snapshots__/SCSS.spec.js.snap, src/components/Breadcrumb/_index.scss, src/components/OverflowMenu/_index.scss, src/components/Tile/_index.scss, src/globals/type/_index.scss
Remove unused Carbon imports and overrides
=> fix: remove unused Carbon imports and overrides

src/globals/deprecate/_index.scss, src/globals/deprecate/index.js, src/globals/grid/_index.scss, src/globals/layout/_index.scss, src/globals/scss-exports/spacing.module.scss, src/globals/theme/_index.scss, src/globals/theme/_mixins.scss, src/globals/type/_index.scss, src/index.scss
Contributes to #978 
Add suppression mechanism for nested deprecation warnings depending on which entry point they're called from
=> build(deprecate): add suppression mechanism

src/components/PanelV2/__tests__/PanelV2.spec.js
Remove accessibility test for deprecated functionality and warnings in test output
=> test(panel): remove accessibility test for deprecated functionality

src/components/Button/__tests__/Button.spec.js
Remove test for [Carbon `field` class that no longer exists](https://github.com/carbon-design-system/carbon/pull/8459)
=> test(button): remove outdated test

jest.config.js
- Accessibility tests timing out occasionally due to network request
- Increase the jest timeout to 20 seconds aligning with C&CS
-
=> build: increase jest timeout to 20 seconds

src/__tests__/scss/__snapshots__/styles-test.js.snap, src/components/Nav/_mixins.scss, src/components/Toolbar/_mixins.scss
Latest changes to nav and toolbar:
Change the chevron icon direction when dropdown is open and closed
Fix hover spacing. The hover was only hovering over 3/4 of the panel
Remove highlighting on selected dropdowns
Increase icon size to 20px
Increase the menu item size to 32px.
- Resolves 
Change the chevron icon direction when dropdown is open and closed
Fix hover spacing. The hover was only hovering over 3/4 of the panel
Remove highlighting on selected dropdowns
Increase icon size to 20px
Increase the menu item size to 32px.
=> Latest changes to nav and toolbar

src/components/ErrorPage/_mixins.scss
n/a
update padding value to use spacing token instead of mini-unit
=> feat(errorpage): update padding value

src/__tests__/scss/__snapshots__/styles-test.js.snap, src/components/Nav/NavList/NavList.js, src/components/Nav/NavList/__tests__/__snapshots__/NavList-test.js.snap, src/components/Nav/__tests__/__snapshots__/Nav-test.js.snap, src/components/Nav/_mixins.scss, src/components/Toolbar/Toolbar.js, src/components/Toolbar/_mocks_/index.js, src/components/__tests__/__snapshots__/publicAPI-test.js.snap
Reverts carbon-design-system/ibm-security#1035
=>  feat(toolbar): 487/allow icons next to dropdowns - Revert

src/__tests__/scss/__snapshots__/styles-test.js.snap, src/components/Nav/NavList/NavList.js, src/components/Nav/NavList/__tests__/__snapshots__/NavList-test.js.snap, src/components/Nav/__tests__/__snapshots__/Nav-test.js.snap, src/components/Nav/_mixins.scss, src/components/Toolbar/Toolbar.js, src/components/Toolbar/_mocks_/index.js, src/components/__tests__/__snapshots__/publicAPI-test.js.snap
Allow icons on nav list items to follow 
- Resolves 487
add icon into navlist but make it optional based on icon prop
-
=> feat(toolbar): Allow an icon to be used for menu dropdowns(optional)

.achecker.yml, src/components/FilterPanel/FilterPanelSearch/FilterPanelSearch.js, src/components/__tests__/__snapshots__/publicAPI-test.js.snap
- Resolves https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/918/checks#step:7:1041
- Pass in `aria-label` to `Search` component in `FilterPanelSearch`
- Align `accessibility-checker` configuration with Cloud & Cognitive
=> fix(filter-panel-search): fix accessibility error

src/components/NonEntitledSection/NonEntitledSection.js, src/components/__tests__/__snapshots__/publicAPI-test.js.snap, src/components/_mocks_/index.js
- add style prop to NonEntitledSection
- express default empty string with single quotes in a mock file
-
=> chore: jsdoc and prop type fixes

src/__tests__/scss/__snapshots__/styles-test.js.snap, src/components/Button/_mixins.scss, src/components/ComboButton/_index.scss, src/components/DataDecorator/_mixins.scss, src/components/TrendingCard/_index.scss, src/globals/motion/_index.scss
Contributes to #973 
- Fix `Button`, `ComboButton`, and some `DataDecorator` warnings
- Update global motion variables to point to Carbon motion tokens
=> chore(stylelint): fix `Button`, `ComboButton`, and some `DataDecorator` warnings

src/components/DataTable/DataTablePagination/DataTablePagination.js
- Mark `onChange` as throw away variable
- Make `componentDidMount` and `paginateRows`  simple class methods
- Destructure params in `paginationChange` and improve JSDoc 
-
=> chore(data-table-pagination): fix eslint error and some cleanup

src/components/ErrorPage/ErrorPage.js, src/components/ScrollGradient/ScrollGradient.js, src/components/Tearsheet/Tearsheet.js, src/components/Wizard/Wizard.js, src/components/__tests__/__snapshots__/publicAPI-test.js.snap
- ErrorPage: Remove unused `labels` prop
- ScrollGradient, Tearsheet, Wizard: mark some vars as throw away
-
=> chore: various eslint fixes

src/components/PageLayouts/stories/index.js
- Contributes to #1072 
Fix ESLint error for 'Page Layouts'
=> docs(page-layouts): fix eslint error

src/components/FilterPanel/LEGACY_FilterPanel/FilterSubcategory/FilterSubcategory.js
- Resolves incomplete dependencies in effect hook
- Make list `listContainer` a reference
- Add `shouldTruncate` to dependencies
-
=> chore(filter-subcategory): properly declare useEffect dependencies

src/globals/rtl/_index.scss, src/globals/theme/_index.scss, src/globals/theme/_theme.scss
- Resolves https://github.com/carbon-design-system/ibm-cloud-cognitive/runs/3310382048?check_suite_focus=true#step:7:209
Fix Stylelint errors and warnings for themes and RTL globals
=> chore(stylelint): fix theme import error, fix RTL warning

src/__tests__/scss/__snapshots__/styles-test.js.snap, src/components/ICA/_index.scss
Contributes to #973 
Restructure ICA styles to fix Stylelint warnings.
=> chore(ica): fix Stylelint warnings

src/__tests__/scss/__snapshots__/styles-test.js.snap, src/components/Nav/_mixins.scss, src/components/Panel/_mixins.scss, src/components/PanelV2/_mixins.scss, src/components/SearchBar/_index.scss, src/components/Shell/_mixins.scss, src/components/Tearsheet/TearsheetSmall/_mixins.scss
Resolves #973
Fix various `Nav`, `Panel`, `SearchBar`, `Shell` and `TearsheetSmall` Stylelint warnings
=> chore(stylelint): fix various component warnings

.stylelintrc, src/components/Nav/_mixins.scss
Contributes to #973
-  Fix overlooked `Nav` Stylelint warning
- Use strict Stylelint configuration
=> refactor(nav): fix overlooked Stylelint warning

.storybook/index.js, src/components/LayoutModules/stories/Library.stories.mdx, src/components/Overview/stories/Overview.stories.mdx, src/components/Overview/stories/index.js
- Resolves #
- Create Overview where it lets users know entire repo is deprecated
- Start development server and verify changes
=> chore: deprecate  entire repo

src/components/Overview/stories/Overview.stories.mdx
- Resolves typo in Storybook headline
- 
- 
-
=> update to fix typo
